#Configuration File for mindsquare Yoda
[app]
title = "mindsquare Yoda"
model = "claude-3-haiku-20240307" #Enter your Anthropic Modell of choice - empty will default to gpt-3.5-turbo

[app.texts]
initial_message = "Frage mich etwas über mindsquare AG" #Initial message from Yoda if you start the chat
source = "Quellen" #Headline to mention the source section where Yoda list all sources used for the reply
